apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-driven-azure.fullname" . }}-inventory
  labels:
    {{- include "event-driven-azure.labels" . | nindent 4 }}
    app.kubernetes.io/component: inventory-service
spec:
  {{- if not .Values.inventoryService.autoscaling.enabled }}
  replicas: {{ .Values.inventoryService.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: inventory-service
  template:
    metadata:
      labels:
        {{- include "event-driven-azure.labels" . | nindent 8 }}
        app.kubernetes.io/component: inventory-service
    spec:
      serviceAccountName: {{ include "event-driven-azure.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: inventory-service
          image: {{ include "event-driven-azure.image" (dict "root" . "repository" .Values.inventoryService.image.repository) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "event-driven-azure.fullname" . }}-config
                  key: KAFKA_BROKER
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "event-driven-azure.secretName" . }}
                  key: RABBITMQ_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "event-driven-azure.secretName" . }}
                  key: REDIS_URL
          livenessProbe:
            exec:
              command: ["node", "-e", "process.exit(0)"]
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            {{- toYaml .Values.inventoryService.resources | nindent 12 }}
