apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-driven-azure.fullname" . }}-order
  labels:
    {{- include "event-driven-azure.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  type: {{ .Values.orderService.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: order-service
  ports:
    - name: http
      port: {{ .Values.orderService.service.port }}
      targetPort: http
